### ISSUE TITLE
cannot load such file -- zip

### ISSUE THREAD

**Issue by halostatue** [rubylibs/quik#1]
At line [quik.rb:14](https://github.com/rubylibs/quik/blob/master/lib/quik.rb#L14),  you `require 'zip'` which does not work if you have an older version of rubyzip installed (pre 1.0), because that version of `rubyzip` defines its load at `zip/zip`.

I suggest that the `rubyzip` dependency at [Rakefile:24](https://github.com/textkit/textutils/blob/master/Rakefile#L24) be modified to require at least 1.0.

This issue is blocked by textkit/textutils#2.

**Comment by geraldb** [comment]
Thanks for trying quik. Great catch. Thanks. Will do.Cheers.

**Comment by geraldb** [comment]
FYI: An new textutils update now includes your change. Thanks again.
