### ISSUE TITLE
IDEA: add remove .zip file

### ISSUE THREAD

**Issue by StartZeroGnu** [rubylibs/quik#2]
Hi!

it would be possible to add a step to remove the .zip file?

```
## </lib/quik/builder.rb>

if @pak
   unzip_dir = "./#{name}"

   ## step 1: unzip templates
  @pak.unzip( unzip_dir )

 ## step 2: merge templates (using hash/config settings)
  m = Quik::Merger.new
  m.merge( unzip_dir, h )

 ## step 3: remove .zip file

end
```

I propose as an idea because I do not know programming in ruby, it would be possible?

Thanks, bye!.

**Comment by geraldb** [comment]
Thanks. I added your suggestion to the new [ideas page](https://github.com/quikstart/quik/blob/master/IDEAS.md).  For now the philosophiy is to be on the safe-side and not delete files / zips. Cheers.
